import Head from 'next/head'
import AppHeader from '@/components/header/AppHeader'
import Hero from '@/components/home/Hero'
import { Box } from '@mui/material'

export default function Home() {
  return (
    <>
      <Head>
        <title>Viet Tran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader />
      <Box
        className={'bg-grid'}
        sx={{
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
        }}
      ></Box>
      <main>
        <Hero />
      </main>
    </>
  )
}
