import Head from 'next/head'
import Hero from '@/components/home/Hero'
import WorkPreview from '@/components/home/WorkPreview'
import BlogPreview from '@/components/home/BlogPreview'
import Services from '@/components/home/Services'

export default function Home() {
  return (
    <>
      <Head>
        <title>Viet Tran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <WorkPreview />
      <BlogPreview />
      <Services />
    </>
  )
}
